{% set name = "Babel" %}
{% set version = "2.12.1" %}
{% set sha256 = "cc2d99999cd01d44420ae725a21c9e3711b3aadc7976d6147f622d8581963455" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pybabel = babel.messages.frontend:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - pytz
  run:
    - python >=3.6
    - pytz

test:
  imports:
    - babel
    - babel.localtime
    - babel.messages

  commands:
    - pybabel --help

about:
  home: http://babel.pocoo.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Utilities to internationalize and localize Python applications
  description: |
    Babel is an integrated collection of utilities that assist in
    internationalizing and localizing Python applications, with an emphasis
    on web-base applications.
  doc_url: http://babel.pocoo.org/en/latest/#user-documentation
  doc_source_url: https://github.com/python-babel/babel/blob/master/docs/index.rst
  dev_url: https://github.com/python-babel/babel

extra:
  recipe-maintainers:
    - frol
    - nehaljwani
