{% set name = "Babel" %}
{% set version = "2.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1f3554ca26605fe173f3de0c65f750f5a42f924499bf134de6423582298e316

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pybabel = babel.messages.frontend:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytz
    - wheel
  run:
    - python
    - pytz >=2015.7  # [py<39]

test:
  imports:
    - babel
    - babel.localtime
    - babel.messages
  requires:
    - pip
  commands:
    - pip check
    - pybabel --help

about:
  home: https://babel.pocoo.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utilities to internationalize and localize Python applications
  description: |
    Babel is an integrated collection of utilities that assist in
    internationalizing and localizing Python applications, with an emphasis
    on web-base applications.
  doc_url: https://babel.pocoo.org/
  doc_source_url: https://github.com/python-babel/babel/blob/master/docs/index.rst
  dev_url: https://github.com/python-babel/babel

extra:
  recipe-maintainers:
    - frol
    - nehaljwani
