{% set name = "babel" %}
{% set version = "2.17.0" %}
{% set sha256 = "0c54cffb19f690cdcc52a3b50bcbf71e07a808d1c80d549f2459b9d2cf0afb9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pybabel = babel.messages.frontend:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pytz >=2015.7

test:
  imports:
    - babel
    - babel.localtime
    - babel.messages
  commands:
    - pip check
    - pybabel --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://babel.pocoo.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Utilities to internationalize and localize Python applications
  description: |
    Babel is an integrated collection of utilities that assist in
    internationalizing and localizing Python applications, with an emphasis
    on web-base applications.
  doc_url: http://babel.pocoo.org/en/latest/#user-documentation
  doc_source_url: https://github.com/python-babel/babel/blob/master/docs/index.rst
  dev_url: https://github.com/python-babel/babel

extra:
  recipe-maintainers:
    - frol
    - nehaljwani
    - thewchan
