travis:
  secure:
    BINSTAR_TOKEN: wu/eg2AupE5jqk44y/YQXDqXsMwOkCJOEFu5W54zVH/JOAXszYy+yHcYB6F0+PU7RY6heD5xJ0Rkpi+l87AKe1+47H3Nzih3EcKZEiDkEhZEyw2GVtfi0ghCcFXyzrXcZdFwWXytGf/V8eNuzTfAchHXBNNEJfXC/Gl124YKPyB6GLVVNspTZ7dmH9l7ceVn9pqXqQI43mpNivPrdrHXVXEWfCfCR+Sees4owKElRr5ZvJSknqs6gL854vMHxTdJQ7eBcejO4G/ON3p0BQrE1qWsA9abixROnqTJbDGJmNWA2mKajq9XS/9kee+wHP+sVXcV4IuL11FcLjuqb/xtw/86C2q+FFN/VxLuPWUrgZpHGecAQZ71cNzUU9tUZAswtLaa9zyr1l6sPOZv7L4FO1uC6I1K4gjNom/yXDAwPQheopkaOsBduP0jSkr80KMxqV6uCjMwB4hmUGVC1x8tq+0X0LvD3LnCI+jmajYO3LNDLwp54NglFLm9cxCMDrN9Bp8Q5+bCdWbO5CmWEq9YKKMHf350SFu8oKJbyEefOPXRQZWIdFvlKUhKx/W1ILfqO2+2F7nC47dTNZA4Ze3W+fSp1wqpk2fmf0mR1HZBwuQz9xaEXWW/erhklgx08TpfSznjWO1IV5HFDVg7OH1oH7pyF9r+o7vmW9ZENC86k+M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
